import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarInset, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { Separator } from "@radix-ui/react-dropdown-menu";
import { Breadcrumb, BreadcrumbItem, BreadcrumbLink, BreadcrumbList, BreadcrumbPage, BreadcrumbSeparator } from "@/components/ui/breadcrumb";
import { Bot, BrainCogIcon, Coins, DatabaseZapIcon, FilePlus, FlaskConicalIcon, FolderSearch2, HardHatIcon, House, LayoutTemplateIcon } from "lucide-react";
import ReactScanWrapper from "./reactScanWrapper";
import { Toaster } from "@/components/ui/toaster";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Modify the transform function to store icon keys
// const transformDirectoryToNav = (
//   structure: Record<string, any>,
//   basePath: string = ""
// ): any[] => {
//   const result: any[] = [];

//   const findIconKey = (key: string) => {
//     switch (key.toLowerCase()) {
//       case "create":
//         return "FilePlus";
//       case "main":
//         return "House";
//       case "explore":
//         return "FolderSearch2";
//       case "api":
//         return "BrainCogIcon";
//       case "dashboard":
//         return "LayoutTemplateIcon";
//       case "db":
//         return "DatabaseZapIcon";
//       case "obras":
//         return "HardHatIcon";
//       case "presupuesto":
//         return "Coins";
//       case "uitest":
//         return "FlaskConicalIcon";
//       default:
//         return "Bot"; // Default icon key
//     }
//   };

//   for (const key in structure) {
//     if (key === "files") continue;

//     const folder = structure[key];
//     const files = folder.files || [];
//     const hasPageFile = files.includes("page.tsx");
//     const subfolders = Object.keys(folder).filter(k => k !== "files");

//     if (hasPageFile) {
//       const iconKey = findIconKey(key);

//       const items = transformDirectoryToNav(folder, `${basePath}/${key}`);
//       result.push({
//         title: capitalizeFirstLetter(key),
//         url: `${basePath}/${key}`.replace(/\/+/g, "/"),
//         iconKey: iconKey, // Store icon key
//         items: [
//           {
//             title: "Main",
//             url: `${basePath}/${key}`.replace(/\/+/g, "/"),
//             iconKey: "House", // Use the Main icon key for the "Main" page
//           },
//           ...items
//         ]
//       });
//     } else if (typeof folder === "object") {
//       const iconKey = findIconKey(key);

//       result.push({
//         title: capitalizeFirstLetter(key),
//         url: `${basePath}/${key}`.replace(/\/+/g, "/"),
//         iconKey: iconKey, // Store icon key
//         items: transformDirectoryToNav(folder, `${basePath}/${key}`)
//       });
//     }
//   }

//   return result;
// }

// // Map icon keys back to components
// const iconMap = {
//   FilePlus,
//   House,
//   FolderSearch2,
//   BrainCogIcon,
//   LayoutTemplateIcon,
//   DatabaseZapIcon,
//   HardHatIcon,
//   Coins,
//   FlaskConicalIcon,
//   Bot
// };
// // Function to map icon keys back to components
// const mapIconsToComponents = (navItems: { iconKey: keyof typeof iconMap; items: { iconKey: keyof typeof iconMap }[] }[]) => {
//   return navItems.map(item => ({
//     ...item,
//     icon: iconMap[item.iconKey],
//     items: item.items.map(subItem => ({
//       ...subItem,
//       icon: iconMap[subItem.iconKey]
//     }))
//   }));
// };

const capitalizeFirstLetter = (string: string) => {
  return string.charAt(0).toUpperCase() + string.slice(1);
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const res = await fetch("http://localhost:3000/api/getDirectory", {
  //   cache: "no-store",
  // });

  // const data = await res.json();

  // const transformed = transformDirectoryToNav(data);

  // console.log('transformed', transformed)

  const mapped = [
    {
      "title": "Api",
      "url": "/api",
      "iconKey": "BrainCogIcon",
      "items": [
        {
          "title": "Certificaciones",
          "url": "/api/certificaciones",
          "iconKey": "Bot",
          "items": []
        },
        {
          "title": "Certificados",
          "url": "/api/certificados",
          "iconKey": "Bot",
          "items": [
            {
              "title": "[id]",
              "url": "/api/certificados/[id]",
              "iconKey": "Bot",
              "items": []
            }
          ]
        },
        {
          "title": "ConstructionElements",
          "url": "/api/constructionElements",
          "iconKey": "Bot",
          "items": []
        },
        {
          "title": "ElementCategory",
          "url": "/api/elementCategory",
          "iconKey": "Bot",
          "items": []
        },
        {
          "title": "Empresas",
          "url": "/api/empresas",
          "iconKey": "Bot",
          "items": []
        },
        {
          "title": "GetDirectory",
          "url": "/api/getDirectory",
          "iconKey": "Bot",
          "items": []
        },
        {
          "title": "Inspectores",
          "url": "/api/inspectores",
          "iconKey": "Bot",
          "items": []
        },
        {
          "title": "Obras",
          "url": "/api/obras",
          "iconKey": "HardHatIcon",
          "items": [
            {
              "title": "[id]",
              "url": "/api/obras/[id]",
              "iconKey": "Bot",
              "items": [
                {
                  "title": "Presupuestos",
                  "url": "/api/obras/[id]/presupuestos",
                  "iconKey": "Bot",
                  "items": []
                }
              ]
            },
            {
              "title": "[obraId]",
              "url": "/api/obras/[obraId]",
              "iconKey": "Bot",
              "items": []
            }
          ]
        },
        {
          "title": "Presupuestos",
          "url": "/api/presupuestos",
          "iconKey": "Bot",
          "items": [
            {
              "title": "TableData",
              "url": "/api/presupuestos/tableData",
              "iconKey": "Bot",
              "items": []
            },
            {
              "title": "[id]",
              "url": "/api/presupuestos/[id]",
              "iconKey": "Bot",
              "items": []
            }
          ]
        },
        {
          "title": "Proyectistas",
          "url": "/api/proyectistas",
          "iconKey": "Bot",
          "items": []
        },
        {
          "title": "TagsWithElements",
          "url": "/api/tagsWithElements",
          "iconKey": "Bot",
          "items": []
        }
      ]
    },
    {
      "title": "Certificados",
      "url": "/certificados",
      "iconKey": "Bot",
      "items": [
        {
          "title": "Main",
          "url": "/certificados",
          "iconKey": "House"
        },
        {
          "title": "New",
          "url": "/certificados/new",
          "iconKey": "Bot",
          "items": [
            {
              "title": "Main",
              "url": "/certificados/new",
              "iconKey": "House"
            }
          ]
        },
        {
          "title": "[id]",
          "url": "/certificados/[id]",
          "iconKey": "Bot",
          "items": [
            {
              "title": "Main",
              "url": "/certificados/[id]",
              "iconKey": "House"
            }
          ]
        }
      ]
    },
    {
      "title": "Dashboard",
      "url": "/dashboard",
      "iconKey": "LayoutTemplateIcon",
      "items": [
        {
          "title": "Main",
          "url": "/dashboard",
          "iconKey": "House"
        }
      ]
    },
    {
      "title": "Db",
      "url": "/db",
      "iconKey": "DatabaseZapIcon",
      "items": [
        {
          "title": "Certificaciones",
          "url": "/db/certificaciones",
          "iconKey": "Bot",
          "items": [
            {
              "title": "Main",
              "url": "/db/certificaciones",
              "iconKey": "House"
            }
          ]
        },
        {
          "title": "ConstructionElements",
          "url": "/db/constructionElements",
          "iconKey": "Bot",
          "items": [
            {
              "title": "Main",
              "url": "/db/constructionElements",
              "iconKey": "House"
            }
          ]
        },
        {
          "title": "Empresas",
          "url": "/db/empresas",
          "iconKey": "Bot",
          "items": [
            {
              "title": "Main",
              "url": "/db/empresas",
              "iconKey": "House"
            }
          ]
        },
        {
          "title": "Inspectores",
          "url": "/db/inspectores",
          "iconKey": "Bot",
          "items": [
            {
              "title": "Main",
              "url": "/db/inspectores",
              "iconKey": "House"
            }
          ]
        },
        {
          "title": "Obras",
          "url": "/db/obras",
          "iconKey": "HardHatIcon",
          "items": [
            {
              "title": "Main",
              "url": "/db/obras",
              "iconKey": "House"
            }
          ]
        },
        {
          "title": "Proyectistas",
          "url": "/db/proyectistas",
          "iconKey": "Bot",
          "items": [
            {
              "title": "Main",
              "url": "/db/proyectistas",
              "iconKey": "House"
            }
          ]
        },
        {
          "title": "TagsWithElements",
          "url": "/db/tagsWithElements",
          "iconKey": "Bot",
          "items": [
            {
              "title": "Main",
              "url": "/db/tagsWithElements",
              "iconKey": "House"
            }
          ]
        }
      ]
    },
    {
      "title": "Obras",
      "url": "/obras",
      "iconKey": "HardHatIcon",
      "items": [
        {
          "title": "Main",
          "url": "/obras",
          "iconKey": "House"
        },
        {
          "title": "Create",
          "url": "/obras/create",
          "iconKey": "FilePlus",
          "items": [
            {
              "title": "Main",
              "url": "/obras/create",
              "iconKey": "House"
            }
          ]
        },
        {
          "title": "[id]",
          "url": "/obras/[id]",
          "iconKey": "Bot",
          "items": [
            {
              "title": "Main",
              "url": "/obras/[id]",
              "iconKey": "House"
            }
          ]
        }
      ]
    },
    {
      "title": "Presupuesto",
      "url": "/presupuesto",
      "iconKey": "Coins",
      "items": [
        {
          "title": "Main",
          "url": "/presupuesto",
          "iconKey": "House"
        },
        {
          "title": "All",
          "url": "/presupuesto/all",
          "iconKey": "Bot",
          "items": [
            {
              "title": "Main",
              "url": "/presupuesto/all",
              "iconKey": "House"
            }
          ]
        },
        {
          "title": "Components",
          "url": "/presupuesto/components",
          "iconKey": "Bot",
          "items": []
        },
        {
          "title": "[id]",
          "url": "/presupuesto/[id]",
          "iconKey": "Bot",
          "items": [
            {
              "title": "Main",
              "url": "/presupuesto/[id]",
              "iconKey": "House"
            }
          ]
        }
      ]
    },
    {
      "title": "Uitest",
      "url": "/uitest",
      "iconKey": "FlaskConicalIcon",
      "items": [
        {
          "title": "Main",
          "url": "/uitest",
          "iconKey": "House"
        },
        {
          "title": "Button",
          "url": "/uitest/button",
          "iconKey": "Bot",
          "items": [
            {
              "title": "Main",
              "url": "/uitest/button",
              "iconKey": "House"
            }
          ]
        }
      ]
    }
  ]

  return (
    <html lang="en">
      <head>
        {/* rest of your scripts go under */}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReactScanWrapper>
          <SidebarProvider>
            <AppSidebar mappedData={mapped as any} />
            <SidebarInset>
              <header className="flex h-16 shrink-0 items-center gap-2 transition-[width,height] ease-linear group-has-[[data-collapsible=icon]]/sidebar-wrapper:h-12">
                <div className="flex items-center gap-2 px-4">
                  <SidebarTrigger className="-ml-1" />
                  <Separator className="mr-2 h-4" />
                  <Breadcrumb>
                    <BreadcrumbList>
                      <BreadcrumbItem className="hidden md:block">
                        <BreadcrumbLink href="#">
                          Building Your Application
                        </BreadcrumbLink>
                      </BreadcrumbItem>
                      <BreadcrumbSeparator className="hidden md:block" />
                      <BreadcrumbItem>
                        <BreadcrumbPage>Data Fetching</BreadcrumbPage>
                      </BreadcrumbItem>
                    </BreadcrumbList>
                  </Breadcrumb>
                </div>
              </header>

              {children}
            </SidebarInset>
          </SidebarProvider>
        </ReactScanWrapper>
        <Toaster />
      </body>
    </html>
  );
}
